[package]
name = "torrust"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.5"
eyre = "0.6.12"
reqwest = "0.12.22"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
url = "2.5.4"
